server:
  port: 8010

spring:
  application:
    name: content-center

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/content_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: root123
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    # 整合 nacos
    nacos:
      discovery:
        # 指定 nacos server 地址
        server-addr: 39.102.66.189:8848
        # 命名空间，先在 nacos 控制台创建，需要配置id
        # namespace: 79c61e60-afb4-447a-b957-7f651d63d619
        # 指定集群名称：对指定微服务的一个虚拟划分 ： NJ-南京机房 BJ-北京机房
        cluster-name: BJ
        metadata:
          # 本实例版本
          version: v1
          # 允许调用实例的版本
          target-version: v1

    # 整合 sentinel 测试的时候先临时注释掉
#    sentinel:
#      transport:
#        # 指定 sentinel 控制台的地址
#        dashboard: localhost:8849
#        # dashboard: 39.102.66.189:8849
#      filter:
#        # 关闭对Spring MVC断点的保护 false:关闭 true:打开
#        enabled: true

    # 整合 Spring Cloud Stream RocketMQ
    stream:
      rocketmq:
        binder:
          name-server: 39.102.66.189:9876

      bindings:
        output:
          # 用来指定 topic
          destination: stream-test-topic

  # 用于处理多个FeignClient存在相同调用服务名的情况
  main:
    allow-bean-definition-overriding: true

# 配置通过ribbon调用user-center服务的细粒度
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 开启饥饿加载 ：clients 支持细粒度 ：clients: xxx,xxx,xxx
ribbon:
  eager-load:
    enabled: true
    #clients: user-center

logging:
  level:
    # com.itmuch 包下所有的
    com.itmuch: debug
    # 通过代码方式配置 Feign 的日志级别，需要在 yml 中进行如下配置，如果是 info 级别则不会打印任何日志
    # 可以通过下面这种方式配置多个具体的Client：如 UserCenterFeignClient1 、UserCenterFeignClient2 ...
    # com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
    # 低版本的时候，引入spring-cloud-starter-stream-rocketmq会一直打印日志，设定级别解决。本版本没有问题
    # com.alibab.nacos: error

feign:
  client:
    config:
      # 想要调用的微服务的名称
      # user-center:
      # 全局配置
      default:
        loggerLevel: full

  httpclient:
    # 让 feign 使用 apache httpclient 作请求
    enabled: true
    # feign 的最大连接数
    max-connections: 200
    # feign 的单个路径最大连接数
    max-connections-per-route: 50

  # feign 支持 okhttp 配置 需要把 httpclient 中 enable 注释掉，连接数依旧放在 httpclient 下
  # okhttp:
  #   enabled: true

  # 为 feign 整合 sentinel
  sentinel:
    enabled: true

# 暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 配置rocketmq
rocketmq:
  name-server: 39.102.66.189:9876
  producer:
    # 小坑：必须指定group
    group: test-group
